addons:
  postgresql: 10.3
before_script:
  #- cp config/database.yml.travis config/database.yml
  - psql -c 'create database pgapp_test;' -U postgres
  - gem install bundler
dist: trusty
language: ruby
rvm:
  - 2.5.0
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
